### PR TITLE
Get new exercises in GetUpdatableExercises

### PR DESCRIPTION
**Pull request by Salmela**

### CODE REVIEW

**Comment by Salmela** [comment]
I am still testing these changes so please don't merge it.

**Comment by Salmela** [comment]
I verified that these changes work on actual course.

**Comment by jamo** [comment]
Great work!
However, I have a few thoughts and feature requests on this implementation. 
1. I would prefer to categorize the updates and new exercises, so that when we ask for users which exercises she wants to download update it's clear which exercises are new and which updates. So maybe instead return a UpdateResult (can be inner class) that contains `ImmutableList<Exercise>` for new exercises and updates.
2. I dislike the `O(n^n)` implementation, with a lookup table we could make this `O(n)`. This might be helpful: https://github.com/testmycode/tmc-core/blob/master/src/main/java/fi/helsinki/cs/tmc/core/domain/ExerciseKey.java

**Comment by Salmela** [comment]
Please don't merge this pull request yet. I found typo in one of the unit tests.

**Comment by Salmela** [comment]
This pull request can be now merged. I got the problem fixed.

**Comment by jamo** [comment]
Awoseme. Nice work!

**Pull request merged**
